### ISSUE TITLE
Transparency "true", doesn't have effect.

### ISSUE THREAD

**Issue by FilipPyrek** [playif/play_phaser#24]
Game game = new Game(window.innerWidth, window.innerHeight, WEBGL, '', new Main(), true);

There is no difference between true or false, when i checked it in Main.create it is always false.

I took a look at Game constructor, mistake is probably there. :) :+1:

**Comment by TheIceMageX50** [comment]
This was fixed with #26 it would seem, right?

**Comment by FilipPyrek** [comment]
When I wrote this, it hasn't worked. So, probably not. :)

**Comment by TheIceMageX50** [comment]
But you created this on January 12th. The commit merged in #26 was on the 20th.

**Comment by FilipPyrek** [comment]
OK, so probably it works :+1:
